version: "3.4"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: argonms
  center:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "8383:8383"
    command: >
      bash -c "
        mysql -h db --password=testing argonms < sql/argon.sql &&
        bin/launch_center.sh
      "
  login:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      - $DATA_DIR:/app/wz
    depends_on:
      - center
      - db
    ports:
      - "8484:8484"
    command: bash -c "sleep 15 && bin/launch_login.sh"
  game:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      - $DATA_DIR:/app/wz
    depends_on:
      - center
      - db
    ports:
      - "7575:8585"
      - "7576:8586"
      - "7577:8587"
    command: bash -c "sleep 15 && bin/launch_game.sh"
  shop:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      - $DATA_DIR:/app/wz
    depends_on:
      - center
      - db
    ports:
      - "8787:8787"
    command: bash -c "sleep 15 && bin/launch_shop.sh"
